export const mockData = [
  {
    id: 1,
    company: "104資訊科技",
    position: "前端工程師",
    status: "已錄取",
    interviewDate: "2024/8/08",
    updateDate: "2024/8/28",
    isSelected: false,
  },
  {
    id: 2,
    company: "104資訊科技",
    position: "前端工程師",
    status: "未錄取",
    interviewDate: "2024/8/08",
    updateDate: "2024/8/28",
    isSelected: false,
  },
  {
    id: 3,
    company: "104資訊科技",
    position: "前端工程師",
    status: "已錄取",
    interviewDate: "2024/8/08",
    updateDate: "2024/8/28",
    isSelected: false,
  },
  {
    id: 4,
    company: "ABC科技",
    position: "後端工程師",
    status: "等待結果",
    interviewDate: "2024/8/15",
    updateDate: "2024/8/20",
    isSelected: false,
  },
  {
    id: 5,
    company: "XYZ公司",
    position: "UI設計師",
    status: "未錄取",
    interviewDate: "2024/8/10",
    updateDate: "2024/8/22",
    isSelected: false,
  },
];
